services:
  loki:
    image: grafana/loki:latest
    restart: "no"
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config/loki-config.yaml:/etc/loki/loki-config.yaml
      - loki_data:/data/loki
    command: -config.file=/etc/loki/loki-config.yaml
    deploy:
      resources:
        limits:
          memory: 500M
      replicas: &logs ${LOGS_REPLICAS:-1}
    labels:
      - logging=promtail      

  promtail:
    image: grafana/promtail:latest
    restart: 'no'
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail/config/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/promtail-config.yaml
    deploy:
      resources:
        limits:
          memory: 100M
      replicas: *logs
    depends_on:
      - loki
    labels:
      - logging=promtail

  grafana:
    image: grafana/grafana:latest
    restart: 'no'
    user: "0"
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources/
    deploy:
      resources:
        limits:
          memory: 100M
      replicas: *logs
    depends_on:
      - loki
    labels:
      - logging=promtail

volumes: 
  kafka_data:
  loki_data:
  grafana_data: